const BooksTypes = { 
    GET_BOOKS: '@books/GET_BOOKS', 
    GET_BOOKS_SUCCESS: '@books/GET_BOOKS_SUCCESS', 
    GET_BOOKS_FAILURE: '@books/GET_BOOKS_FAILURE', 
    GET_BOOKS_BY_CATEGORY: '@books/GET_BOOKS_BY_CATEGORY', 
    GET_BOOKS_BY_CATEGORY_SUCCESS: '@books/GET_BOOKS_BY_CATEGORY_SUCCESS', 
    GET_BOOKS_BY_CATEGORY_FAILURE: '@books/GET_BOOKS_BY_CATEGORY_FAILURE', 
    CLEAR_BOOKS: '@books/CLEAR_BOOKS',
}

export default BooksTypes;